# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='couorder',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Orden para mostrar el country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clireplychannel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Websocket'),
        ),
    ]
