# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0003_auto_20170529_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='citorder',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Order to show city on profile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cliusername',
            field=models.CharField(blank=True, max_length=14, verbose_name='@username'),
        ),
        migrations.AlterField(
            model_name='country',
            name='couorder',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Order to show country'),
        ),
    ]
