# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-30 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0004_auto_20170529_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True, 'ordering': ['citorder']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True, 'ordering': ['couorder']},
        ),
        migrations.AddField(
            model_name='bodytype',
            name='bodorder',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Order to show bodytype on profile'),
        ),
    ]
