# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0005_auto_20170530_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='inbactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
