# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0007_deniedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplan',
            name='paypath',
            field=models.ImageField(default='promotions/default.png', upload_to='promotions'),
        ),
    ]
