# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0008_payplan_paypath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clidescription',
            field=models.CharField(blank=True, max_length=650, null=True, verbose_name='About'),
        ),
    ]
