# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0009_auto_20170614_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picthumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
