# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 20:06
from __future__ import unicode_literals

import dateSite.models.client
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0010_picture_picthumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picthumb',
            field=models.ImageField(blank=True, null=True, upload_to=dateSite.models.client.get_user_thumb_folder),
        ),
    ]
