# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateSite', '0011_auto_20170626_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payplan',
            name='tofcode',
        ),
        migrations.RemoveField(
            model_name='record',
            name='clicodemain',
        ),
        migrations.RemoveField(
            model_name='record',
            name='clicodesecondary',
        ),
        migrations.RemoveField(
            model_name='record',
            name='purcode',
        ),
        migrations.RemoveField(
            model_name='record',
            name='roocode',
        ),
        migrations.RemoveField(
            model_name='record',
            name='suscode',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='paycode',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purdateend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purdatestart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PayPlan',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='TypeOffer',
        ),
    ]
